"""
Voice smoke test — verify the JENSEN_VOICE_SIGNATURE in lib/persona.ts
produces drafts that actually sound like Jensen.

Doesn't require deploy. Calls Anthropic directly with the production
system prompt and 5 sample briefs. Outputs to specs/001-export-mining/
VOICE-SMOKE-OUTPUT.md for operator eyeball.
"""
import json, os, re, subprocess, sys, urllib.request

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
PERSONA_TS = os.path.join(ROOT, "lib", "persona.ts")
OUT_MD = os.path.join(ROOT, "specs", "001-export-mining", "VOICE-SMOKE-OUTPUT.md")

ANTHROPIC_KEY = subprocess.run(
    ["security", "find-generic-password", "-a", "rinq-anthropic", "-s", "rinq-anthropic-key", "-w"],
    capture_output=True, text=True
).stdout.strip()
assert ANTHROPIC_KEY, "no anthropic key in keychain"


def load_voice_signature():
    """Extract the JENSEN_VOICE_SIGNATURE constant from persona.ts."""
    src = open(PERSONA_TS).read()
    m = re.search(r"const JENSEN_VOICE_SIGNATURE = `(.+?)`;", src, re.DOTALL)
    assert m, "couldn't find JENSEN_VOICE_SIGNATURE block"
    return m.group(1)


SYSTEM = """You are Rencontre, the private concierge and chief of staff for Jensen, founder of La Rencontre, a luxury F&B hospitality consultancy in Dubai.

DRAFTING AS JENSEN. When Jensen asks you to write something AS HIM, in his voice, for him to send, shift to his signature below.

""" + load_voice_signature() + """

STYLE. Never use em-dashes. Use commas, periods, colons. Write in plain prose, no markdown."""

BRIEFS = [
    {
        "label": "partnership follow-up",
        "ask": "Draft me a follow-up email to a hospitality brand owner I met two weeks ago about joining our 4,000 AED six-month partnership. Their name is Reza, they own a Dubai-based wellness brand. We last spoke at a Sohum event. Mention the LinkedIn exposure, website listing, and the partner dinner.",
    },
    {
        "label": "Upaya invitation",
        "ask": "Draft a WhatsApp message inviting a curated guest, Maya, to the next Upaya prelude evening. Include the dress code (dress to impress with a feminine touch) and that it's invitation only.",
    },
    {
        "label": "polite no",
        "ask": "Draft a reply turning down a partnership offer from a hotel brand that doesn't fit our positioning. The contact is Sarah. Keep it warm, leave the door open, no specifics about why.",
    },
    {
        "label": "Sohum class caption",
        "ask": "Write an Instagram caption for a new Tai Chi class at Sohum Wellness Sanctuary, Wednesday evenings, AED 250 per class. Keep it short, soulful, hospitality-grade.",
    },
    {
        "label": "staff brief",
        "ask": "Draft a short message to my SIRO F&B team asking for status on the Refuel Lab implementation. Direct, numbered questions, hospitality-COO tone.",
    },
]


def call(brief: str) -> str:
    req = urllib.request.Request(
        "https://api.anthropic.com/v1/messages",
        method="POST",
        headers={
            "x-api-key": ANTHROPIC_KEY,
            "anthropic-version": "2023-06-01",
            "content-type": "application/json",
        },
        data=json.dumps({
            "model": "claude-sonnet-4-6",
            "max_tokens": 700,
            "system": SYSTEM,
            "messages": [{"role": "user", "content": brief}],
        }).encode(),
    )
    with urllib.request.urlopen(req, timeout=60) as r:
        body = json.loads(r.read())
    return "".join(b.get("text", "") for b in body.get("content", []))


def main():
    lines = ["# Voice Smoke Test — does Rencontre sound like Jensen?", ""]
    lines.append("Generated by `scripts/openai-export/voice_smoke.py`. Uses the live `JENSEN_VOICE_SIGNATURE` block from `lib/persona.ts` against Claude Sonnet 4.6 (production model class). Read each output: does it sound like Jensen would write it?")
    lines.append("")
    for b in BRIEFS:
        print(f"  → {b['label']}", flush=True)
        try:
            draft = call(b["ask"])
        except Exception as e:
            draft = f"(error: {e})"
        lines.append(f"## {b['label']}")
        lines.append("")
        lines.append(f"**Brief:** {b['ask']}")
        lines.append("")
        lines.append("**Rencontre's draft (in Jensen's voice):**")
        lines.append("")
        for line in draft.strip().split("\n"):
            lines.append("> " + line)
        lines.append("")
        # quick lints
        em = draft.count("—") + draft.count("–")
        lines.append(f"_em-dashes: {em} (must be 0 per Law 5)_")
        lines.append("")
        lines.append("---")
        lines.append("")

    with open(OUT_MD, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"\nwrote {OUT_MD}")


if __name__ == "__main__":
    main()
